"use client";
import {Plus,Trash2,Save} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import type {Scorecard} from '@/lib/ai/schema';
export default function ScorecardEditor({value,onChange,onSave,busy}:{value:Scorecard;onChange:(v:Scorecard)=>void;onSave:()=>void;busy:boolean}){
 const sum=value.dimensions.reduce((s,d)=>s+Number(d.weight),0);
 const lines=(key:'must_have'|'nice_to_have',text:string)=>onChange({...value,[key]:text.split('\n')});
 return <div className="card-editor"><div className="section-heading"><div><h2>岗位评分卡</h2><p className="muted">确认真正重要的能力，让每一份简历按同一标准评分。</p></div><span className={sum===100?'weight-total':'weight-total invalid'}>总权重 {sum}% / 100%</span></div><div className="dimension-header"><span>评分维度与判断标准</span><span>权重</span></div>{value.dimensions.map((d,i)=><div className="dimension-edit" key={d.id}><div><Input aria-label={'维度 '+(i+1)+' 名称'} value={d.name} onChange={e=>onChange({...value,dimensions:value.dimensions.map((x,n)=>n===i?{...x,name:e.target.value}:x)})}/><Textarea aria-label={d.name+'判断标准'} value={d.rubric} rows={2} onChange={e=>onChange({...value,dimensions:value.dimensions.map((x,n)=>n===i?{...x,rubric:e.target.value}:x)})}/></div><Input aria-label={d.name+'权重'} type="number" min={1} max={100} value={d.weight} onChange={e=>onChange({...value,dimensions:value.dimensions.map((x,n)=>n===i?{...x,weight:Number(e.target.value)}:x)})}/><Button aria-label={'删除'+d.name} variant="ghost" onClick={()=>onChange({...value,dimensions:value.dimensions.filter((_,n)=>n!==i)})}><Trash2 size={16}/></Button></div>)}<Button variant="outline" disabled={value.dimensions.length>=12} onClick={()=>onChange({...value,dimensions:[...value.dimensions,{id:crypto.randomUUID(),name:'',weight:5,rubric:''}]})}><Plus size={16}/>添加维度</Button><div className="two-cols requirements"><label>Must-have · 必须关注的条件<small>每行一条，缺少信息与明确不满足分别判断</small><Textarea rows={5} value={value.must_have.join('\n')} onChange={e=>lines('must_have',e.target.value)}/></label><label>Nice-to-have · 加分条件<small>每行一条，补充岗位偏好</small><Textarea rows={5} value={value.nice_to_have.join('\n')} onChange={e=>lines('nice_to_have',e.target.value)}/></label></div><div className="editor-footer"><p>保存后创建新版本，已有候选人保留原评分版本。</p><Button className="primary" disabled={busy||sum!==100||!value.dimensions.length} onClick={onSave}><Save size={16}/>{busy?'保存中…':'确认并保存评分卡'}</Button></div></div>
}
