import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,BriefcaseBusiness,Check,CheckCheck,ChevronDown,ChevronRight,CircleHelp,FileCheck2,FileText,FolderOpen,LayoutDashboard,LoaderCircle,Plus,RefreshCw,Search,Settings2,ShieldCheck,SlidersHorizontal,Sparkles,Trash2,Upload,X} from 'lucide-react';
import {api,json} from './api';
import {activeTask,dimensionNames,emptyRequirements,sortResumes,statusNames} from './types';
import type {Evidence,Job,Match,ModelConfig,Requirements,Resume,Task} from './types';

const categories=['全部','优先查看','备选','不太匹配','待补充信息','分析失败'];
const date=(t:number)=>new Date(t*1000).toLocaleDateString('zh-CN');
const badgeClass=(c:string)=>c==='优先查看'?'good':c==='备选'?'blue':c==='不太匹配'?'muted':'amber';
type Notify=(s:string,bad?:boolean)=>void;

export default function App(){
  const [page,setPage]=useState<'jobs'|'workspace'|'settings'>('jobs');
  const [jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState(localStorage.getItem('resume-job')||'');
  const [config,setConfig]=useState<ModelConfig|null>(null),[loading,setLoading]=useState(true);
  const [notice,setNotice]=useState<{text:string;bad:boolean}|null>(null);
  const [editing,setEditing]=useState<Job|'new'|null>(null);
  const notify=useCallback<Notify>((text,bad=false)=>setNotice({text,bad}),[]);
  const refresh=useCallback(async()=>{const [j,c]=await Promise.all([api<Job[]>('/jobs'),api<ModelConfig>('/model-config')]);setJobs(j);setConfig(c);setSelected(s=>j.some(x=>x.id===s)?s:j[0]?.id||'');},[]);
  useEffect(()=>{refresh().catch(e=>notify(e.message,true)).finally(()=>setLoading(false));},[refresh,notify]);
  useEffect(()=>{localStorage.setItem('resume-job',selected);},[selected]);
  const current=jobs.find(j=>j.id===selected);
  function openJob(job:Job){setSelected(job.id);setEditing(null);setPage('workspace');}
  return <div className="shell">
    <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('jobs');setEditing(null);}}><span className="brand-icon"><FileCheck2 size={23}/></span><span>简历筛选助手<small>RESUME ASSISTANT</small></span></a>
      <div className="nav-caption">工作空间</div><nav aria-label="主导航">
        <button className={page==='jobs'?'nav active':'nav'} onClick={()=>{setPage('jobs');setEditing(null);}}><BriefcaseBusiness size={19}/>岗位管理<span className="nav-count">{jobs.length}</span></button>
        <button className={page==='workspace'?'nav active':'nav'} onClick={()=>setPage('workspace')}><LayoutDashboard size={19}/>匹配工作台</button>
        <button className={page==='settings'?'nav active':'nav'} onClick={()=>setPage('settings')}><Settings2 size={19}/>模型配置</button></nav>
      <div className="sidebar-bottom"><div className="local-label"><span className="status-dot"/>本机工作空间</div><p>岗位与简历保存在本机<br/>分析时通过已配置模型处理</p><button className="model-status" onClick={()=>setPage('settings')}><span className={config?.key_set?'status-dot':'status-dot pending'}/>{config?.key_set?'模型已配置':'模型待配置'}<ChevronRight size={14}/></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><span>工作空间</span><ChevronRight size={14}/><strong>{page==='jobs'?'岗位管理':page==='workspace'?'匹配工作台':'模型配置'}</strong><div className="topbar-right"><span className="version">MVP 1.0</span><div className="avatar">我</div></div></header>
      <main>{notice&&<div role={notice.bad?'alert':'status'} className={'notice '+(notice.bad?'error':'')}><span>{notice.text}</span><button aria-label="关闭提示" onClick={()=>setNotice(null)}><X size={17}/></button></div>}
      {loading?<div className="empty"><LoaderCircle className="spin"/>正在连接本机服务…</div>:page==='settings'?<ConfigPage config={config} refresh={refresh} notify={notify}/>:page==='jobs'?(editing?<JobEditor job={editing==='new'?null:editing} onCancel={()=>setEditing(null)} onSaved={async j=>{await refresh();openJob(j);}} notify={notify}/>:<>
        <div className="page-heading"><div><div className="eyebrow">YOUR ROLES</div><h1>岗位管理 <span className="heading-count">{jobs.length}</span></h1><p>先明确岗位要求，再从每份简历中找到匹配的依据。</p></div><button className="primary" onClick={()=>setEditing('new')}><Plus size={17}/>新建岗位</button></div>
        <div className="overview-strip"><div><BriefcaseBusiness/><span>在管岗位<strong>{jobs.length}</strong></span></div><div><FileText/><span>岗位简历总数<strong>{jobs.reduce((s,j)=>s+(j.resume_count||0),0)}</strong></span></div><div><Sparkles/><span>正在处理<strong>{jobs.reduce((s,j)=>s+(j.active_count||0),0)}</strong></span></div></div>
        {jobs.length?<div className="job-grid">{jobs.map(job=><article className="job-card" key={job.id}><div className="card-top"><span className="job-icon"><BriefcaseBusiness size={22}/></span><span className={'badge '+(job.confirmed?'good':'amber')}>{job.confirmed?'要求已确认':'待确认要求'}</span></div><h2>{job.name}</h2><p className="job-excerpt">{job.jd_text||'尚未填写岗位描述'}</p><div className="tags">{job.requirements.skills.slice(0,3).map((s,i)=><span key={i}>{s}</span>)}</div><div className="card-meta"><span><FileText size={14}/>{job.resume_count||0} 份简历</span><span>{date(job.created_at)}</span></div><div className="card-actions"><button onClick={()=>{setSelected(job.id);setEditing(job);}}><SlidersHorizontal size={15}/>编辑要求</button><button className="text-primary" onClick={()=>openJob(job)}>进入工作台<ArrowRight size={15}/></button></div></article>)}</div>:<div className="empty large"><div className="empty-icon"><BriefcaseBusiness size={30}/></div><h2>从第一个岗位开始</h2><p>粘贴或上传 JD，确认技能与经历要求，<br/>即可批量分析 PDF、DOCX 简历。</p><button className="primary" onClick={()=>setEditing('new')}><Plus size={16}/>创建第一个岗位</button><div className="empty-steps"><span>01 明确岗位</span><ChevronRight size={14}/><span>02 上传简历</span><ChevronRight size={14}/><span>03 核对依据</span></div></div>}
        <div className="footnote"><ShieldCheck size={15}/>评分辅助确定查看顺序，最终判断由你完成。</div>
      </>):current?<Workspace key={current.id} job={current} jobs={jobs} onSelect={setSelected} onEdit={()=>{setEditing(current);setPage('jobs');}} notify={notify} refreshJobs={refresh}/>:<div className="empty large"><FolderOpen size={36}/><h2>还没有可匹配的岗位</h2><button className="primary" onClick={()=>{setPage('jobs');setEditing('new');}}>新建岗位<ArrowRight size={16}/></button></div>}
      </main></div>
  </div>;
}

function JobEditor({job,onCancel,onSaved,notify}:{job:Job|null;onCancel:()=>void;onSaved:(j:Job)=>Promise<void>;notify:Notify}){
  const [saved,setSaved]=useState(job),[name,setName]=useState(job?.name||''),[jd,setJd]=useState(job?.jd_text||'');
  const [requirements,setRequirements]=useState<Requirements>(job?.requirements||emptyRequirements());
  const [busy,setBusy]=useState(false),[task,setTask]=useState<Task|null>(null),[extracted,setExtracted]=useState<Requirements|null>(null);
  const file=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(!job)return;api<Task[]>('/tasks?job_id='+job.id).then(tasks=>{const last=tasks.find(t=>t.task_type==='parse_jd');if(last){setTask(last);if(last.status==='succeeded'&&last.output?.job_version===job.version)setExtracted(last.output.requirements||null);}}).catch(e=>notify(e.message,true));},[job,notify]);
  useEffect(()=>{if(!activeTask(task))return;let stopped=false;const timer=setInterval(()=>{api<Task>('/tasks/'+task!.id).then(t=>{if(stopped)return;setTask(t);if(t.status==='succeeded'){setExtracted(t.output?.requirements||null);notify('岗位要求已提取，请应用并核对后确认。');}else if(t.status==='failed'||t.status==='interrupted')notify(t.error?.message||'岗位解析失败',true);}).catch(e=>notify(e.message,true));},2000);return()=>{stopped=true;clearInterval(timer);};},[task,notify]);
  async function persist(confirmed:boolean){
    const data={name,jd_text:jd,requirements,confirmed};
    const j=saved?await api<Job>('/jobs/'+saved.id,json('PATCH',{...data,expected_version:saved.version})):await api<Job>('/jobs',json('POST',data));
    setSaved(j);return j;
  }
  async function parse(){setBusy(true);try{const j=await persist(false);const t=await api<{task_id:string}>('/jobs/'+j.id+'/parse',{method:'POST'});setTask(await api<Task>('/tasks/'+t.task_id));setExtracted(null);}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function save(){setBusy(true);try{const j=await persist(true);notify('岗位要求已确认并保存。');await onSaved(j);}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function upload(f:File){setBusy(true);try{const form=new FormData();form.append('file',f);const result=await api<{text:string}>('/files/extract',{method:'POST',body:form});setJd(result.text);notify('JD 正文已导入。');}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  const working=busy||activeTask(task);
  return <><div className="page-heading"><div><div className="eyebrow">DEFINE THE ROLE</div><h1>{job?'编辑岗位':'新建岗位'}</h1><p>原文与确认后的要求同时保存，匹配以你确认的要求为准。</p></div><button onClick={onCancel}>返回岗位列表</button></div>
    <div className="editor-grid"><section className="panel"><div className="section-title"><span className="step">01</span><h2>岗位描述</h2></div><label>岗位名称<input value={name} maxLength={120} onChange={e=>setName(e.target.value)} placeholder="例如：Python 后端工程师" disabled={working}/></label><div className="label-row"><label htmlFor="jd">JD 原文</label><button className="text-primary small" disabled={working} onClick={()=>file.current?.click()}><Upload size={14}/>从文件导入</button><input hidden ref={file} type="file" accept=".pdf,.docx" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/></div><textarea id="jd" className="jd-input" value={jd} maxLength={60000} onChange={e=>setJd(e.target.value)} placeholder={'粘贴职位描述，包含工作职责、技能要求和任职条件…'} disabled={working}/><div className="field-hint">支持 PDF / DOCX，每份不超过 10 MB</div><button className="primary full" disabled={working||!name.trim()||!jd.trim()} onClick={()=>void parse()}>{working?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>}提取岗位要求</button>{task&&<p className="field-hint">最近解析：{statusNames[task.status]}{task.error?' · '+task.error.message:''}</p>}</section>
    <section className="panel"><div className="section-title"><span className="step">02</span><h2>核对岗位要求</h2><span className="badge muted">可手动填写</span></div>{extracted&&<div className="inline-banner"><span>AI 提取结果已就绪</span><button onClick={()=>{setRequirements({...extracted,conditions:[...extracted.conditions,...requirements.conditions.filter(c=>!extracted.conditions.some(e=>e.id===c.id))]});setExtracted(null);}}>应用到下方</button></div>}
      {(['skills','experience','other'] as const).map(k=><label key={k}>{dimensionNames[k]} <small>{k==='skills'?'40%':k==='experience'?'35%':'15%'}</small><textarea value={requirements[k].join('\n')} onChange={e=>setRequirements({...requirements,[k]:e.target.value.split('\n')})} placeholder={k==='skills'?'每行一项，例如：熟练使用 Python':k==='experience'?'每行一项，例如：有后端服务开发经验':'每行一项，例如：岗位要求的资格证书'} disabled={working}/></label>)}
      <div className="label-row"><h3>额外筛选条件</h3><button className="text-primary small" disabled={working} onClick={()=>setRequirements({...requirements,conditions:[...requirements.conditions,{id:crypto.randomUUID(),text:'',kind:'must'}]})}><Plus size={15}/>添加条件</button></div>
      {requirements.conditions.map((c,i)=><div className="condition-edit" key={c.id}><select aria-label={`条件 ${i+1} 类型`} value={c.kind} disabled={working} onChange={e=>setRequirements({...requirements,conditions:requirements.conditions.map(x=>x.id===c.id?{...x,kind:e.target.value as 'must'|'bonus'}:x)})}><option value="must">必须满足</option><option value="bonus">加分项</option></select><input aria-label={`条件 ${i+1} 内容`} value={c.text} maxLength={1000} disabled={working} placeholder="填写岗位相关条件" onChange={e=>setRequirements({...requirements,conditions:requirements.conditions.map(x=>x.id===c.id?{...x,text:e.target.value}:x)})}/><button aria-label={`删除条件 ${i+1}`} disabled={working} onClick={()=>setRequirements({...requirements,conditions:requirements.conditions.filter(x=>x.id!==c.id)})}><X size={15}/></button></div>)}
      <p className="field-hint">没有要求的维度自动分配权重；额外加分占 10%。</p><div className="editor-footer"><span><CircleHelp size={15}/>确认前请核对提取内容</span><button className="primary" disabled={working||!name.trim()} onClick={()=>{setRequirements(r=>({...r,skills:r.skills.map(s=>s.trim()).filter(Boolean),experience:r.experience.map(s=>s.trim()).filter(Boolean),other:r.other.map(s=>s.trim()).filter(Boolean)}));void saveClean();}}><CheckCheck size={17}/>确认并保存</button></div>
    </section></div></>;
  async function saveClean(){// Use the cleaned snapshot directly; React state updates are asynchronous.
    setBusy(true);try{const cleaned={...requirements,skills:requirements.skills.map(s=>s.trim()).filter(Boolean),experience:requirements.experience.map(s=>s.trim()).filter(Boolean),other:requirements.other.map(s=>s.trim()).filter(Boolean)};const data={name,jd_text:jd,requirements:cleaned,confirmed:true};const j=saved?await api<Job>('/jobs/'+saved.id,json('PATCH',{...data,expected_version:saved.version})):await api<Job>('/jobs',json('POST',data));setSaved(j);notify('岗位要求已确认并保存。');await onSaved(j);}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
}

function Workspace({job,jobs,onSelect,onEdit,notify,refreshJobs}:{job:Job;jobs:Job[];onSelect:(s:string)=>void;onEdit:()=>void;notify:Notify;refreshJobs:()=>Promise<void>}){
  const [rows,setRows]=useState<Resume[]>([]),[busy,setBusy]=useState(false),[category,setCategory]=useState('全部'),[sort,setSort]=useState('score_desc');
  const [detail,setDetail]=useState<Match|null>(null),[deleting,setDeleting]=useState<Resume|null>(null),[dragging,setDragging]=useState(false);
  const [uploadErrors,setUploadErrors]=useState<string[]>([]),[loaded,setLoaded]=useState(false);
  const uploadRef=useRef<HTMLInputElement>(null);
  const refresh=useCallback(async()=>{setRows(await api<Resume[]>('/jobs/'+job.id+'/resumes'));setLoaded(true);},[job.id]);
  useEffect(()=>{refresh().catch(e=>notify(e.message,true));},[refresh,notify]);
  const running=rows.some(r=>activeTask(r.task));
  useEffect(()=>{if(!running)return;const t=setInterval(()=>{refresh().catch(e=>notify(e.message,true));},2000);return()=>clearInterval(t);},[running,refresh,notify]);
  async function upload(files:FileList|File[]){if(!files.length)return;setBusy(true);setUploadErrors([]);try{const form=new FormData();form.append('job_id',job.id);Array.from(files).forEach(f=>form.append('files',f));const response=await api<{files:{filename:string;error:{message:string}|null}[]}>('/resumes',{method:'POST',body:form});setUploadErrors(response.files.filter(f=>f.error).map(f=>`${f.filename}：${f.error!.message}`));const count=response.files.filter(f=>!f.error).length;notify(`已接收 ${count} 份简历，可开始匹配。`);await refresh();await refreshJobs();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function start(ids:string[],force=false){setBusy(true);try{await api('/jobs/'+job.id+'/matches',json('POST',{resume_ids:ids,force}));await refresh();notify('匹配任务已提交，刷新页面后仍可查看进度。');}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function retry(task:Task){setBusy(true);try{await api('/tasks/'+task.id+'/retry',{method:'POST'});await refresh();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  const visible=sortResumes(rows,category,sort),done=rows.filter(r=>r.task?.status==='succeeded'&&r.match&&!r.match.stale).length;
  const pending=rows.filter(r=>!activeTask(r.task)&&(!r.match||r.match.stale||['failed','interrupted'].includes(r.task?.status||'')));
  return <><div className="page-heading"><div><div className="eyebrow">MATCHING WORKSPACE</div><h1>简历匹配工作台</h1><p>查看匹配程度，更要核对每一条依据。</p></div><div className="job-switch"><BriefcaseBusiness size={17}/><select aria-label="切换岗位" value={job.id} onChange={e=>onSelect(e.target.value)}>{jobs.map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</select></div></div>
    <section className="role-summary"><div><h2>{job.name}<span className={'badge '+(job.confirmed?'good':'amber')}>{job.confirmed?'要求已确认':'待确认'}</span><span className="version">v{job.version}</span></h2><div className="tags">{job.requirements.skills.slice(0,4).map((s,i)=><span key={i}>{s}</span>)}<span>{job.requirements.conditions.filter(c=>c.kind==='must').length} 条硬性条件</span></div></div><button onClick={onEdit}><SlidersHorizontal size={15}/>编辑岗位要求</button></section>
    {!job.confirmed&&<div className="inline-banner">请先确认岗位要求，再开始匹配。<button onClick={onEdit}>去确认<ArrowRight size={14}/></button></div>}
    <section className={'upload-area '+(dragging?'dragging':'')} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(!busy)void upload(e.dataTransfer.files);}}><div className="upload-icon"><Upload size={24}/></div><div><h3>把简历拖到这里，或选择文件上传</h3><p>PDF、DOCX · 每份最大 10 MB · 每批最多 20 份 · 暂不支持扫描件</p></div><button disabled={busy} onClick={()=>uploadRef.current?.click()}><Plus size={16}/>选择简历</button><input ref={uploadRef} hidden type="file" multiple accept=".pdf,.docx" onChange={e=>{if(e.target.files)void upload(e.target.files);e.target.value='';}}/></section>
    {uploadErrors.length>0&&<div className="notice error" role="alert"><ul>{uploadErrors.map(e=><li key={e}>{e}</li>)}</ul></div>}
    <div className="metrics"><Metric label="全部简历" value={rows.length} sub="当前岗位"/><Metric label="已完成分析" value={done} sub={rows.length?`${Math.round(done/rows.length*100)}% 已完成`:'等待上传'}/><Metric label="优先查看" value={rows.filter(r=>r.match?.category==='优先查看'&&!r.match.stale&&r.task?.status==='succeeded').length} sub="岗位匹配分 ≥ 80" green/><Metric label="待补充信息" value={rows.filter(r=>r.match?.category==='待补充信息'&&!r.match.stale).length} sub="需进一步核对"/></div>
    <section className="results-panel"><div className="result-heading"><h2>候选简历<span>{rows.length}</span></h2><button className="primary" disabled={busy||!job.confirmed||!pending.length} onClick={()=>void start(pending.map(r=>r.id))}>{busy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>}开始匹配{pending.length?` · ${pending.length}`:''}</button></div>
    <div className="filters"><div className="filter-tabs" aria-label="分类筛选">{categories.map(c=><button aria-pressed={category===c} className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><select aria-label="结果排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="score_desc">匹配分从高到低</option><option value="score_asc">匹配分从低到高</option><option value="newest">最近上传</option></select></div>
    {running&&<div className="progress-row"><LoaderCircle size={15} className="spin"/>正在逐份分析 · 你可以继续上传或离开此页面<span>{rows.filter(r=>activeTask(r.task)).length} 份处理中</span></div>}
    <div className="table-scroll"><table><thead><tr><th>候选人 / 文件</th><th>匹配分</th><th>分类</th><th>硬性条件</th><th className="reason-col">关键理由</th><th>操作</th></tr></thead><tbody>{visible.map(r=>{const m=r.match,t=r.task,failed=t&&['failed','interrupted'].includes(t.status);return <tr key={r.id}><td><div className="candidate"><span className="file-avatar"><FileText size={19}/></span><div><strong>{r.name||r.filename}</strong><small title={r.filename}>{r.filename}</small></div></div></td><td><span className={'score '+(m?.stale||m?.provisional?'dim':'')}>{m?.total_score??'—'}</span>{m?.provisional&&<small className="block">暂定分</small>}</td><td>{activeTask(t)?<span className="badge blue"><LoaderCircle size={12} className="spin"/>{t!.stage}</span>:failed?<span className="badge amber">{statusNames[t.status]}</span>:m?<><span className={'badge '+badgeClass(m.category)}>{m.category}</span>{m.stale&&<small className="stale">需要重新分析</small>}</>:<span className="badge muted">待分析</span>}</td><td>{m?<span className="hard-counts"><span className="green">{m.hard_counts.met} 满足</span><small>{m.hard_counts.not_met} 不满足 · {m.hard_counts.unknown} 待确认</small></span>:'—'}</td><td className="reason-cell">{failed?t.error?.message:m?.summary||'分析后展示匹配点与缺口'}</td><td><div className="row-actions">{m&&<button className="text-primary small" onClick={()=>api<Match>('/matches/'+m.id).then(setDetail).catch(e=>notify(e.message,true))}>详情<ArrowUpRight size={13}/></button>}{failed?<button className="icon-button" title="重试" aria-label={`重试 ${r.filename}`} disabled={busy} onClick={()=>void retry(t)}><RefreshCw size={14}/></button>:m&&!activeTask(t)&&<button className="icon-button" title="重新分析" aria-label={`重新分析 ${r.filename}`} disabled={busy||!job.confirmed} onClick={()=>void start([r.id],true)}><RefreshCw size={14}/></button>}<button className="icon-button danger" aria-label={`删除 ${r.filename}`} onClick={()=>setDeleting(r)}><Trash2 size={14}/></button></div></td></tr>;})}</tbody></table></div>
    {!visible.length&&<div className="empty table-empty"><FileText size={27}/><h3>{!loaded?'正在读取简历…':rows.length?'当前分类没有简历':'等待你的第一批简历'}</h3><p>{rows.length?'切换分类查看其他结果。':'上传后点击「开始匹配」，查看评分和原文依据。'}</p></div>}
    <div className="table-footer"><span>共 {visible.length} 份 · 待补充信息和过期结果不参与正常排名</span><span>本机自动保存<Check size={13}/></span></div></section>
    <div className="footnote"><CircleHelp size={15}/>匹配分代表岗位相关程度，不代表录用概率。请结合原文判断。</div>
    {detail&&<Detail match={detail} onClose={()=>setDetail(null)}/>}
    {deleting&&<Modal title="删除这份简历？" onClose={()=>setDeleting(null)}><p>将删除「{deleting.filename}」的原文件，以及它在所有岗位中的分析记录。此操作不可撤销。</p><div className="modal-actions"><button onClick={()=>setDeleting(null)}>取消</button><button className="danger-solid" disabled={busy} onClick={async()=>{setBusy(true);try{const response=await api<{warning?:string}>('/resumes/'+deleting.id,{method:'DELETE'});setDeleting(null);await refresh();await refreshJobs();notify(response.warning||'简历及关联结果已删除。',!!response.warning);}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}>确认删除</button></div></Modal>}
  </>;
}

function Metric({label,value,sub,green=false}:{label:string;value:number;sub:string;green?:boolean}){return <div className={'metric '+(green?'metric-green':'')}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>;}

function Modal({title,onClose,children,sheet=false}:{title:string;onClose:()=>void;children:React.ReactNode;sheet?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current!;dialog.showModal();return()=>dialog.close();},[]);
  return <dialog ref={ref} className={sheet?'detail-dialog':'modal'} onCancel={e=>{e.preventDefault();onClose();}} aria-label={title}><div className="dialog-header"><h2>{title}</h2><button aria-label="关闭面板" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}

function Detail({match:m,onClose}:{match:Match;onClose:()=>void}){
  const [tab,setTab]=useState('analysis');
  const blocks=m.resume?.text_blocks||[];
  function quotes(evidence:Evidence[]){return evidence.map((e,i)=><blockquote key={i}><span>{blocks.find(b=>b.id===e.text_block_id)?.location||e.text_block_id}</span>“{e.quote}”</blockquote>);}
  return <Modal title="候选人匹配详情" onClose={onClose} sheet><div className="detail-body"><div className="detail-identity"><span className="file-avatar large"><FileText size={26}/></span><div><h2>{m.resume?.name||m.resume?.filename}</h2><p>{m.resume?.filename}</p></div><a className="button" href={'/api/resumes/'+m.resume_id+'/file'}><ArrowDownToLine size={15}/>原文件</a></div>{m.stale&&<div className="notice error">岗位要求或模型配置已改变，请重新分析；以下为历史结果。</div>}<div className="detail-score"><div><strong>{m.total_score??'—'}</strong><span>{m.provisional?'暂定匹配分':'岗位匹配分'}</span></div><span className={'badge '+badgeClass(m.category)}>{m.category}</span><p>{m.summary}</p></div>
    <div className="detail-tabs"><button className={tab==='analysis'?'selected':''} onClick={()=>setTab('analysis')}>评分与依据</button><button className={tab==='source'?'selected':''} onClick={()=>setTab('source')}>简历原文</button></div>
    {tab==='source'?<div className="source-text">{blocks.map(b=><section key={b.id}><small>{b.location} · {b.id}</small><p>{b.text}</p></section>)}</div>:<><h3 className="detail-section-title">各维度匹配</h3>{m.dimensions.map(d=><section className="dimension" key={d.dimension}><div className="dimension-heading"><h3>{dimensionNames[d.dimension]} <small>权重 {Math.round(m.weights[d.dimension]*100)}%</small></h3><strong>{d.score??'待确认'}</strong></div><div className="score-track"><span style={{width:(d.score||0)+'%'}}/></div><p>{d.reason}</p>{quotes(d.evidence)}</section>)}<h3 className="detail-section-title">筛选条件核对</h3>{m.conditions.length?m.conditions.map(c=>{const condition=m.input_snapshot.requirements.conditions.find(x=>x.id===c.condition_id);return <section className="condition-result" key={c.condition_id}><div><h3>{condition?.text||c.condition_id}</h3><span className={'badge '+(c.status==='met'?'good':c.status==='unknown'?'amber':'muted')}>{c.status==='met'?'满足':c.status==='not_met'?'不满足':'待确认'}</span></div><small>{condition?.kind==='must'?'硬性条件':'加分项'}</small><p>{c.reason}</p>{quotes(c.evidence)}</section>;}):<p className="field-hint">此岗位未设置额外条件。</p>}</>}
    <div className="detail-meta">岗位版本 v{m.job_version} · 模型 {m.model} · {date(m.created_at)}<br/>原文存在性已校验，判断是否合理仍需人工核对。</div></div></Modal>;
}

function ConfigPage({config,refresh,notify}:{config:ModelConfig|null;refresh:()=>Promise<void>;notify:Notify}){
  const [base,setBase]=useState(config?.base_url||''),[model,setModel]=useState(config?.model||''),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[tested,setTested]=useState(false);
  const changed=base!==config?.base_url||model!==config?.model||!!key;
  async function save(){setBusy(true);try{await api('/model-config',json('PUT',{base_url:base,model,api_key:key}));setKey('');setTested(false);await refresh();notify('模型配置已加密保存。');}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function test(){setBusy(true);try{const result=await api<{message:string}>('/model-config/test',{method:'POST'});setTested(true);notify(result.message);}catch(e){setTested(false);notify((e as Error).message,true);}finally{setBusy(false);}}
  return <><div className="page-heading"><div><div className="eyebrow">MODEL CONNECTION</div><h1>模型配置</h1><p>连接你的模型，让岗位要求和简历分析使用同一套配置。</p></div><span className={'badge '+(config?.key_set?'good':'amber')}>{config?.key_set?'已保存配置':'等待配置'}</span></div><div className="config-grid"><section className="panel config-form"><div className="section-title"><span className="job-icon"><Settings2 size={20}/></span><h2>API 连接</h2></div><label>API Base URL<input value={base} type="url" disabled={busy} onChange={e=>{setBase(e.target.value);setTested(false);}} placeholder="https://api.example.com/v1"/></label><p className="field-hint">使用兼容聊天补全的接口地址，保留 /v1，不包含 /chat/completions。</p><label>API Key<input value={key} type="password" autoComplete="new-password" disabled={busy} onChange={e=>setKey(e.target.value)} placeholder={config?.key_set?'已保存 ••••••••，留空保留现有密钥':'填写你的 API Key'}/></label><p className="field-hint">密钥加密保存在本机，保存后只显示掩码。</p><label>模型名称<input value={model} disabled={busy} onChange={e=>{setModel(e.target.value);setTested(false);}} placeholder="填写服务商提供的模型 ID"/></label><div className="config-actions"><button className="primary" disabled={busy||!base.trim()||!model.trim()||(!key&&!config?.key_set)} onClick={()=>void save()}>{busy?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}保存配置</button><button disabled={busy||!config?.key_set||changed} onClick={()=>void test()}><RefreshCw size={15}/>测试连接</button></div>{changed&&config?.key_set&&<p className="field-hint">修改后请先保存，再测试连接。</p>}{tested&&<div className="connection-ok"><CheckCheck size={18}/>连接成功，结构化响应验证通过</div>}</section><aside className="config-guide"><div className="guide-icon"><ShieldCheck size={25}/></div><h2>关于模型调用</h2><p>解析 JD、提取简历事实和判断匹配度会调用你配置的模型。</p><div className="guide-item"><span>01</span><div><strong>先保存，再测试</strong><p>连接测试会验证鉴权、网络及 JSON 输出格式。</p></div></div><div className="guide-item"><span>02</span><div><strong>配置改变后重新分析</strong><p>已有结果保留，工作台会提示重新分析。</p></div></div><div className="guide-item"><span>03</span><div><strong>敏感信息不参与评分</strong><p>匹配前隐藏姓名与联系方式，仅按岗位相关信息判断。</p></div></div><p className="field-hint">模型调用可能产生服务商费用。扫描件 OCR 暂未纳入本版。</p></aside></div></>;
}
