"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from 'react';
import {Upload,Sparkles,ArrowRight,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import Shell from '@/components/workspace-shell';
import {supabaseBrowser} from '@/lib/supabase/browser';
import {api,send} from '@/lib/client';
export default function NewJob(){
 const [form,setForm]=useState({name:'',jd:'',department:'',location:'',level:'',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[configured,setConfigured]=useState<boolean|null>(null),[parsing,setParsing]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{api('status').then(x=>setConfigured(x.ai_configured)).catch(e=>setError(e.message))},[]);
 async function create(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const j=await api('jobs',send(form));location.href='/jobs/'+j.id+'?tab=scorecard'}catch(e){setError((e as Error).message);setBusy(false)}}
 async function readFile(file?:File){if(!file)return;setParsing(true);setError('');try{if(!/\.(pdf|docx)$/i.test(file.name)||!file.size||file.size>10485760)throw Error('仅支持不超过 10 MB 的 PDF / DOCX');const client=supabaseBrowser();const {data:{user}}=await client.auth.getUser();if(!user)throw Error('请先登录');const ext=file.name.toLowerCase().endsWith('.pdf')?'pdf':'docx',storagePath=user.id+'/jd/'+crypto.randomUUID()+'.'+ext;const {error}=await client.storage.from('resumes').upload(storagePath,file,{contentType:ext==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});if(error)throw error;const result=await api('documents',send({storagePath,fileName:file.name}));setForm(v=>({...v,jd:result.text}));}catch(e){setError((e as Error).message)}finally{setParsing(false);if(fileRef.current)fileRef.current.value=''}}
 return <Shell><div className="page-heading"><div><p className="eyebrow">CREATE A ROLE</p><h1>创建岗位</h1><p className="muted">让 AI 理解你的岗位，再由你确认筛选标准。</p></div></div><div className="creation-steps"><b>01 填写岗位</b><ArrowRight size={16}/><span>02 AI 理解岗位</span><ArrowRight size={16}/><span>03 校准评分卡</span></div>{configured===false&&<div className="notice">DeepSeek 尚未连接。可先填写岗位；管理员需在后端配置服务密钥后才能进行真实分析。</div>}<form onSubmit={create} className="create-layout"><section className="panel form-panel"><label>岗位名称 <em>*</em><Input required maxLength={100} placeholder="例如：Agent 产品经理" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="label-with-action"><label htmlFor="jd">岗位描述 JD <em>*</em></label><Button type="button" variant="ghost" disabled={parsing||busy} onClick={()=>fileRef.current?.click()}><Upload size={15}/>{parsing?'解析文件中…':'上传 JD 文件'}</Button></div><input ref={fileRef} hidden type="file" accept=".pdf,.docx" onChange={e=>readFile(e.target.files?.[0])}/><Textarea id="jd" required minLength={30} maxLength={40000} rows={14} placeholder={'粘贴完整岗位描述，建议包含：\n\n• 岗位职责与业务场景\n• 核心技能与经验要求\n• 明确的硬性条件\n• 加分项'} value={form.jd} onChange={e=>setForm({...form,jd:e.target.value})}/><div className="field-hint">支持 PDF / DOCX，最大 10 MB · {form.jd.length.toLocaleString()} / 40,000 字符</div><div className="two-cols">{([['department','部门','例如：AI 产品部'],['location','工作地点','例如：上海'],['level','职级','例如：P6'],['notes','备注','其他需要了解的岗位背景']] as const).map(([key,label,placeholder])=><label key={key}>{label}<span className="optional">选填</span><Input maxLength={key==='notes'?1000:100} value={form[key]} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><Link href="/">取消</Link><Button className="primary" disabled={busy||parsing||configured===false} type="submit">{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {busy?'正在理解岗位，请稍候…':'创建并分析岗位'}</Button></div></section><aside className="create-aside"><div className="aside-icon"><Sparkles size={24}/></div><h2>一个岗位，一套标准</h2><p>AI 会从 JD 中提取岗位画像，生成专属于这个岗位的评分维度。</p><ol><li><b>理解岗位</b><span>核心职责、必备条件和加分项</span></li><li><b>生成评分卡</b><span>按岗位特点分配 100% 权重</span></li><li><b>由你校准</b><span>修改维度与权重，确认后开始筛选</span></li></ol><p className="aside-note">岗位只需深度分析一次。新增简历直接使用已保存的评分标准。</p></aside></form></Shell>
}
